### ISSUE TITLE
How do Hitboxes work?

### ISSUE THREAD

**Issue by markus-wa** [Galaco/studiomodel#16]
Hey :wave:

From what I gather hitboxes of things like doors, boxes and barrels are part of model files as well.

Do you know how to work out if a certain trajectory goes through a model placed in a certain location on the map? (of course the model doesn't hold data about where it's placed, that part would need to be provided by the user)

I'd be happy to contribute some code in this area once I understand how to do this

**Comment by Galaco** [comment]
Hi!
Collision meshes are indeed part of the studio model, and are represented by the .phy format. 
They are optional; in cases where a model does not have a PHY, the engine can still use the bounding box specified in the .mdl data (assuming the level designer explicitly specified this; the default is no collision). It's common for TF2 props to have no collision mesh, but less common for CSGO and other games.

In regards to determining if a trajectory passes through a prop, this would generally be out of scope of this library; this is just a parsing library, it'd be more suited to some sort of VPhysics library than a parser.

But you have 2 options after loading the PHY itself:

##### Use a dedicated physics engine
Since the PHY structure is rather simple it's easy to transform to various Physics engine implementations; the format is essentially just vertices and indices to make up triangle faces.
Here's an example generating Bullet Physics meshes with a working simulation: https://github.com/Galaco/kero/blob/dedc4e04e830cc2597308cbfe9e9bcbe30491fae/physics/collisionStructure.go#L130 ). 
If you were to extract this package: https://github.com/Galaco/kero/tree/dev/framework/physics/collision/bullet, and add the relevant Bullet functions for ray-casting you could more easily load a PHY into Bullet and test for intersection.

##### Write your own ray-cast/collision implementation
Assuming that you're casting a straight line, you can utilise a line-triangle intersection algorithm against each triangle in the collision mesh (e.g. https://en.wikipedia.org/wiki/Möller–Trumbore_intersection_algorithm) after loading the .PHY (and applying the placed model's transformation to them). I believe I implemented this a while back, but no idea if it works; the repository certainly doesn't use it currently: https://github.com/Galaco/kero/blob/dedc4e04e830cc2597308cbfe9e9bcbe30491fae/physics/collision/ray.go#L143.
If your trajectory is non-straight, perhaps it's more difficult, but if you can utilise Bézier curves to split the curve into a series of rays you could likely utilise the same implementation. I haven't investigated this case, that just a thought.
I doubt this suggestion is a particularly efficient implementation, but the complexity should be reasonably low...

I hope this helps though, if I can be of more assistance feel free to ask!

**Comment by markus-wa** [comment]
that's amazing! thanks so much for the detailed answer ❤️ - I'll close this issue for now, but might get back in touch if I have more questions 🙂
